### ISSUE TITLE
Lost class names while transfering .blob file

### ISSUE THREAD

**Issue by Andre-t02Github** [luxonis/tools#110]
Hi team!
I've encountered an issue where the class names from my trained model are lost after converting the model's weights from a .pt file to a .blob file. Instead of the original class names, all labels have been renamed to generic titles such as "Class_0", "Class_1", ..., "Class_10". Could you please provide me with some guidance on how to resolve this?

Below is an example of how the labels currently appear:
"labels": [
    "Class_0",
    "Class_1",
    "Class_2",
    "Class_3",
    "Class_4",
    "Class_5",
    "Class_6",
    "Class_7",
    "Class_8",
    "Class_9",
    "Class_10"
]
I am looking for a way to retain the original class names after the file conversion. Any suggestions or advice would be greatly appreciated.

**Comment by HonzaCuhel** [comment]
Hi @Andre-t02Github,

I've fixed the issue with class names for the conversion of YOLOv8, v9 and v10 in latest PR. Export of YOLOv5 and v7 didn't suffer with this issue. Unfortunately for YOLOv6 and GoldYOLO conversion, the models themselves don't store the class names, therefore we are unable to propagate them to the generated .json file, therefore, you need to manually edit the file.

The fix will be deployed shortly after the approval, I'll inform you once it is deployed. 

Best,
Jan

**Comment by HonzaCuhel** [comment]
As promised, the fix is now deployed to the prod.

**Comment by Andre-t02Github** [comment]
Issue resolved. Thank you for your feedback!

**Comment by HonzaCuhel** [comment]
Happy to help!
