### ISSUE TITLE
Cannot convert yolov5 model at 640px wide

### ISSUE THREAD

**Issue by stephansturges** [luxonis/tools#25]
Hey there,
I have two .pt files, uploaded in this folder:
https://drive.google.com/drive/folders/1Ga9zph3NLmJAzaBBVDQdyBMYmQdyjmvg?usp=sharing

These are both yoloV5 format, trained with the same dataset and parameters except for resolution: one is 320:320 and the other is 640:640

The 320px model works 100% in the online conversion tool at tools.luxonis.com, the 640px model fails with a random error ( "An error occurred
Error while loading model). 

I've tried to reproduce this problem locally by running the app in docker-compose, but this gives me a different error (see screenshot below) an fails to launch with the latest code in this repo.
![Screenshot from 2022-12-12 09-08-37](https://user-images.githubusercontent.com/20320678/206995654-aab39572-6459-45c8-830a-7a768da3a564.png)

Any thoughts?

**Comment by HonzaCuhel** [comment]
Hello,
based on our discussion I'll write a short recapitulation. We have looked into it and found out the issue. The problem was missing dependence on `sparseml` package. So we resolved it by adding the dependency to our tools. 
Best regards,
Jan
