### ISSUE TITLE
Add option to specify shaves

### ISSUE THREAD

**Issue by maxsitt** [luxonis/tools#34]
It would be nice to be able to select the number of shaves the converted .blob model will use. Currently the .blob model will always use 6 shaves and the converted ONNX model has to be uploaded to https://blobconverter.luxonis.com/ to export .blob with different numbers of shaves.

Other option would be to always export the .blob model with e.g. 4, 5 and 6 shaves to enable the user to test and compare them.

**Comment by HonzaCuhel** [comment]
Hi @maxsitt,

thank you for the suggestion! We have just added the option to customize the number of shaves the converted .blob model will use (like in the blobconverter). You can find it under `Advanced options` .  Here's how it looks like:
![image](https://user-images.githubusercontent.com/79118988/222800156-8cd529d5-4c48-46a2-83d5-064b1a67358c.png)
Thanks again,
Jan

**Comment by maxsitt** [comment]
Thanks a lot for implementing the shaves selection that fast @HonzaCuhel! Looks nice and works perfectly :)
