### ISSUE TITLE
Use OpenVINO 2022.1 version

### ISSUE THREAD

**Issue by maxsitt** [luxonis/tools#38]
[`openvino-dev==2022.1.0`](https://github.com/openvinotoolkit/openvino/releases/tag/2022.1.0) has some major updates and improvements (e.g. OpenVINO API 2.0) over previous versions and is used by default by the [BlobConverter](https://blobconverter.luxonis.com/).

If there are no potential drawbacks, it would be great if https://tools.luxonis.com/ would also use this version as default (currently 2021.4.2 is used).

Something else I noticed, which might have no consequences:
[`--reverse_input_channel`](https://github.com/luxonis/tools/blob/master/yolo/exporter.py#L63) is used in the scripts instead of `--reverse_input_channels`.

**Comment by HonzaCuhel** [comment]
Hi @maxsitt,

thank you very much for noticing and reporting and I apologize for the slower reply! I have just deployed a newer version of tools. The update contains a migration from OpenVino 2021.4.2 to 2022.1. and the models are now allowed to have `-` and `_` in their names. To be sure, I have also changed `--reverse_input_channel` to `--reverse_input_channels`, but I haven't found any differences after changing it.

Best
Jan

**Comment by maxsitt** [comment]
Thanks a lot @HonzaCuhel for implementing OpenVINO 2022.1.0 into Luxonis tools!
The new model naming rules also make things easier :)
`--reverse_input_channels` follows the official OpenVINO documentation, but as you say probably has the exact same function.
