### ISSUE TITLE
Issue regarding generating blob file

### ISSUE THREAD

**Issue by drakshayanidesai** [luxonis/tools#40]
I tried with hub.ultralytics with VisDrone dataset with yolovV5m6. It is done but it is throwing error while converting to blob files using tools.luxonis.com(The sheet attached shows the errors). 
Then I tried with yolov5n model on the same dataset but it is showing error while executing in google colab notebook. Please see the errors in the attached sheet. Suggestions?

Regards
Drakshayani
[Luxonis.docx](https://github.com/luxonis/tools/files/10988736/Luxonis.docx)

**Comment by tersekmatija** [comment]
@HonzaCuhel can you look into this? Might be related to `TOOLS-LUXONIS-2N` Sentry issue?

@drakshayanidesai Can you share .pt weights with us please so we can debug the issue further?

**Comment by drakshayanidesai** [comment]
I sent you through mail

**Comment by cafemoloko** [comment]
@drakshayanidesai, could you please send an email to support@luxonis.com? Thank you!

**Comment by HonzaCuhel** [comment]
Hello @drakshayanidesai,

I investigated why the conversion of the `yolovV5m6` fails. I found out that the image size `640x352` is not a multiple of maximum stride `64` (because `352` is not a multiple of `64`), which until now was not shown in the error message in the tools. I apologize for the inconvenience. I have prepared an update for the tools that fixes that. This update will be deployed in the following days. So my suggestions to you are either, please try to export the model with a different image size (e.g., `640x320` or `640x384`) or use a different model, such as `yoloV5n` or `yoloV5s`, which both will run faster on OAK devices than `yolovV5m6` and both can be converted with image size `640x352`.

Best
Jan

**Comment by drakshayanidesai** [comment]
Hi Jan


I tried yoloV5s with VisDrone dataset. But Google colab notebook is running out of time each time I am 
trying. So could you please send the trained model for the same (blob).It is very much in need.

Regards
Drakshayani
On Sat, 18 Mar 2023 04:29:04 +0530 Honza Čuhel  wrote
>
Hello @drakshayanidesai,
I investigated why the conversion of the yolovV5m6 fails. I found out that the image size 640x352 is 
not a multiple of maximum stride 64 (because 352 is not a multiple of 64), which until now was not 
shown in the error message in the tools. I apologize for the inconvenience. I have prepared an update 
for the tools that fixes that. This update will be deployed in the following days. So my suggestions to 
you are either, please try to export the model with a different image size (e.g., 640x320 or 640x384) 
or use a different model, such as yoloV5n or yoloV5s, which both will run faster on OAK devices than 
yolovV5m6 and both can be converted with image size 640x352.
Best

Jan

**Comment by HonzaCuhel** [comment]
Hi @drakshayanidesai,

I am not sure if I understand you correctly, for the investigation described above I have used the standard `yolov6m6` pretrained on the COCO dataset (I haven't trained it or any other model on the VisDrone dataset). So, which model/blob did you exactly mean?

Best
Jan

**Comment by drakshayanidesai** [comment]
Hi Jan

Actually my task is counting number of cyclist, pedestrian in real time using OAK-D. So I want to use 
VisDrone dataset for training model(yoloV5s). Hence trying in colab not able to achieve hence asked 
you.

Regards
Drakshayani

On Mon, 20 Mar 2023 14:08:03 +0530 Honza Čuhel  wrote
>
Hi @drakshayanidesai,
I am not sure if I understand you correctly, for the investigation described above I have used the 
standard yolov6m6 pretrained on the COCO dataset (I haven't trained it or any other model on the 
VisDrone dataset). So, which model/blob did you exactly mean?
Best

Jan

**Comment by drakshayanidesai** [comment]
Hi Jan


I trained model using VisDrone dataset but not able to detect Skatebords. Can you send u r model 
yolov6m6 which trained on COCO. Because in that it is possible. 


Regdars
Drakshayani

On Mon, 20 Mar 2023 14:08:03 +0530 Honza Čuhel  wrote
>
Hi @drakshayanidesai,
I am not sure if I understand you correctly, for the investigation described above I have used the 
standard yolov6m6 pretrained on the COCO dataset (I haven't trained it or any other model on the 
VisDrone dataset). So, which model/blob did you exactly mean?
Best

Jan

**Comment by tersekmatija** [comment]
Hey, @drakshayanidesai 

You should be able to download yolov6m.pt from [official release](https://github.com/meituan/YOLOv6/releases/tag/0.3.0) and use https://tools.luxonis.com/ to export it. Let me know if that works for you..

**Comment by drakshayanidesai** [comment]
Thank you very much

Using the model generated blob file. But unable to succeed. The model yolov6m.pt is pretrained on COCO 
dataset right?

Regdars
Drakshayani

On Thu, 23 Mar 2023 22:58:17 +0530 Matija Teršek  wrote
>
Hey, @drakshayanidesai
You should be able to download yolov6m.pt from official release and use https://tools.luxonis.com/ to 
export it. Let me know if that works for you..

**Comment by tersekmatija** [comment]
Yes correct.

**Comment by drakshayanidesai** [comment]
Let me check
Image shape 640x320 right?

On Fri, 24 Mar 2023 19:36:00 +0530 Matija Teršek  wrote
>
Yes correct.

**Comment by tersekmatija** [comment]
Yes, or 640 x 352 should be closer to 16:9 aspect ratio.

**Comment by drakshayanidesai** [comment]
Hi

It is working fine for me. Thank you very much for your support. My target task is counting no of 
pedestrian and cyclist moving left/right. I know counting but directionality based not sure how to do.

Regards
Drakshayni

On Fri, 24 Mar 2023 20:13:34 +0530 Matija Teršek  wrote
>
Yes, or 640 x 352 should be closer to 16:9 aspect ratio.

**Comment by tersekmatija** [comment]
You could use our [object tracker](https://docs.luxonis.com/projects/api/en/latest/components/nodes/object_tracker/) node after Yolo to track the detected objects. [Here's an example](https://docs.luxonis.com/projects/api/en/latest/samples/ObjectTracker/object_tracker/) using a different type of object detector which you can modify. Then you need to look when object passes certain line/coordinates to increment the counter. We also have a fully working example [here](https://github.com/luxonis/depthai-experiments/tree/master/gen2-cumulative-object-counting).

I am closing this issue since the main problem has been resolved. Feel free to open a new issue in the corresponding repository if the examples I linked above don't work for you :)

**Comment by drakshayanidesai** [comment]
Thank you very much your support


On Mon, 27 Mar 2023 15:57:06 +0530 Matija Teršek  wrote
>
You could use our object tracker node after Yolo to track the detected objects. Here's an example using 
a different type of object detector which you can modify. Then you need to look when object passes 
certain line/coordinates to increment the counter. We also have a fully working example here.
I am closing this issue since the main problem has been resolved. Feel free to open a new issue in the 
corresponding repository if the examples I linked above don't work for you :)

**Comment by drakshayanidesai** [comment]
Hi 

I need your guidance for "sunlight on trail" detection using Luxonis.


Regards
Drakshayani

On Mon, 27 Mar 2023 15:57:06 +0530 Matija Teršek  wrote
>
Closed #40 as completed.

**Comment by tersekmatija** [comment]
Hey @drakshayanidesai , since it's not related to this issue, feel free to reach out to us on Discord, [Discuss](https://discuss.luxonis.com/), or open a new GitHub issue in the appropriate repository.
