### ISSUE TITLE
License

### ISSUE THREAD

**Issue by florczakraf** [luxonis/tools#47]
What is the license for this codebase? I can't find a standard LICENSE file or any mentions in the README file.

**Comment by tersekmatija** [comment]
Hey, thanks for catching that. We'll add it in the next commit. Should be GPL-3.0 since it includes the code base of other Yolo models. CC @HonzaCuhel

**Comment by HonzaCuhel** [comment]
Hi @florczakraf, 
thank you for reporting that! We've just added the license, in the end we have decided to use GNU Affero General Public License v3.0 (APGL-3.0), which is almost identical to GPL-3.0 and YoloV5 and YoloV8 use it.
Best,
Jan
