### ISSUE TITLE
YOLOv8s conversion bug

### ISSUE THREAD

**Issue by ahmed-gaal** [luxonis/tools#56]
Converting the YOLOv8s variant renders a error `Error while loading model`. Other variants of the YOLOv8 model works just fine

**Comment by maxsitt** [comment]
Same error for YOLOv8n (nano) model. I'm using the latest version (Ultralytics YOLOv8.0.113).

**Comment by tersekmatija** [comment]
Thanks, a recent change in Ultralytics package caused the newer versions to be incompatible. If you are using our training tutorials, you can easily revert to an older commit of repository like in the first code block [here](https://colab.research.google.com/github/luxonis/depthai-ml-training/blob/update-yolov8-training/colab-notebooks/YoloV8_training.ipynb).

We are working on a fix for the latest version and will update you when available. 
CC @HonzaCuhel

**Comment by maxsitt** [comment]
Thanks for the quick workaround @tersekmatija @HonzaCuhel!

At least for me the better option seems to be `%pip install -q ultralytics==8.0.110`. Installing from cloned repo in editable mode installs the package to `/content/ultralytics`, which can lead to problems, e.g. when trying to use the roboflow package for dataset import.

I tested the conversion and deployment with version 8.0.110 and everything works fine.

**Comment by HonzaCuhel** [comment]
@ahmed-gaal, @Krishna18698 , @maxsitt 

I have just deployed a newer version of tools that should fix the problem that you had. I apologize for the inconvenience.

Best,
Jan
